### ISSUE TITLE
HTML string with DOCTYPE declaration causes a parsing error

### ISSUE THREAD

**Issue by macdonst** [kristoferjoseph/enhance#3]
The following input:

```javascript
const html = require('@begin/enhance')()
console.log(html`<!DOCTYPE html><hello-world greeting="Well hi!"></hello-world>`)
```

Throws an exception:

```
TypeError: Cannot read properties of undefined (reading '1')
    at html (…/node_modules/@begin/enhance/index.js:12:46)
    at handler (…/index.js:141:19)
    at async combined …/node_modules/@architect/functions/src/http/async/index.js:36:20)
```

It would be nice if the DOCTYPE was just ignored.

**Comment by kristoferjoseph** [comment]
This is an issue with the parse 5 parser.
I will file a bug there.
